### ISSUE TITLE
Adding words to Whisper dictionary to increase recognisability

### ISSUE THREAD

**Issue by Abdurrafey-Siddiqui** [sam-ulrich1/i-swear-ill-stop#2]
hey could you make something like where we can add words to the whisper dictionary or whatever it is so that it can recognise. Since like for example in some audio, a person might say a word in a different language but I want whisper to write it as a transliterated version in English. But whisper would most likely transcribe it incorrectly.

Example: In Arabic كيف حالك
transliterated: Kayfa Haluk (manually add these words so whisper can recognise)

**Comment by sam-ulrich1** [comment]
Could this be achieved by adding it to the [bad_words.txt](https://github.com/sam-ulrich1/i-swear-ill-stop/blob/main/bad_words.txt) file?

My thoughts overall are that this should be pretty straight forward. If you don't use the `--english` flag then the models are multi-lang (I think, correct me if I'm wrong). Which would allow you to use the original Arabic كيف حالك. I can say from personal experience, I have seen the model output native Arabic and Korean text when I was working on the sliding window buffer. I had some incorrect parameters that were jumbling the audio and confusing the model. My main concern here is the single word constraint that currently exists in this implementation. Right now only single words are checked for not multi-word phrases. We can definitely fix that but it is something that should be considered.

**Comment by Abdurrafey-Siddiqui** [comment]
I get this error when I try to install the dependencies using pip install -r requirements.txt
`ERROR: Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
Installing collected packages: dbus-python
    Running setup.py install for dbus-python ... error
    ERROR: Command errored out with exit status 1:`

and the error continues on...

**Comment by sam-ulrich1** [comment]
Are you on linux? Currently the codebase is only built for linux (dbus is a linux thing). You can remove the `dbus` package from the main file and then remove `dbus-python` from the requirements if you would like. Make sure to remove the notification code if you do

**Comment by Abdurrafey-Siddiqui** [comment]
ok ive done that and now the error is gone. But when i'm running the app using py main.y, im confused what exactly is it running since i didnt upload an audio file yet, and it keeps running for a while (didn't output anything)

**Comment by sam-ulrich1** [comment]
It is a real time system that connects to a microphone. It's purpose is to help me stop swearing so it listens to the mic on my computer and beeps when I swear. So first check that you have a mic plugged into your computer. Then run it with the `--verbose` flag to print the raw output from Whisper.
