### ISSUE TITLE
Realtime detection from computer audio to detect and mute bad words before you can hear them

### ISSUE THREAD

**Issue by DonFlymoor** [sam-ulrich1/i-swear-ill-stop#3]
If you could apply this to computer audio and mute bad words from videos, audiobooks, and perhaps even live conversations that would be great. Perhaps it could delay the audio by however long it takes to detect the words, and mute your computer for a short time.

**Comment by sam-ulrich1** [comment]
That would be cool! Sorry I just saw this. Are you think a man-in-the-middle like system interface or for the program to be directly execute on a particular audio sample

**Comment by DonFlymoor** [comment]
I think hooking into the system's audio as a virtual speaker would be the most useful, so a man-in-the-middle would work best. Having an option to delay the display by the amount of time it takes to detect swears would be useful as well for videos, although that might be somewhat difficult to implement

**Comment by sam-ulrich1** [comment]
While it sounds really cool that definitely is a large undertaking. Unfortunately, I don't have the time to work on something that large but feel free to take a stab at it if you'd like!
