### ISSUE TITLE
Sam what's wrong with you?

### ISSUE THREAD

**Issue by realazizk** [sam-ulrich1/i-swear-ill-stop#4]
You shouldn't say the N word...
https://github.com/sam-ulrich1/i-swear-ill-stop/blob/a2dce475a55ee3067af16659089738420927e330/bad_words.txt#L43

**Comment by sam-ulrich1** [comment]
Lol, I refer you to my source for the list
https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
